### ISSUE TITLE
VMInfo SetStatus resume functionality

### ISSUE THREAD

**Issue by Oren-C** [Corsinvest/cv4pve-api-dotnet#10]
Is there a reason why in Corsinvest.ProxmoxVE.Api.Extension.VM.VMInfo.SetStatus resume is not an available case considering Suspend is implemented? 

Just curious if there's a reason for that or if just hasn't been implemented yet, either way I figure I could always handle that in my own code.

**Comment by franklupo** [comment]
forgotten and to give
