### ISSUE TITLE
Creating new HttpClient for each request

### ISSUE THREAD

**Issue by dhmhd** [Corsinvest/cv4pve-api-dotnet#18]
While analyzing the source code, I came across the following line:

https://github.com/Corsinvest/cv4pve-api-dotnet/blob/433b01f5c527a70abad2d49919800ee7a3337b79/src/Corsinvest.ProxmoxVE.Api/PveClientBase.cs#L192

However, according to Microsoft documentation, it's strongly recommended to reuse the same copy of HttpClient:

> HttpClient is intended to be instantiated once per application, rather than per-use

https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0

If I understand correctly, the using statement ensures that the HttpClient instance is disposed, preventing resource leaks. However, creating a new instance of HttpClient every time can lead to performance issues and even resource exhaustion.

Could you please explain why it's done that way, using "using"?

**Comment by franklupo** [comment]
Did your memory run out?

**Comment by dhmhd** [comment]
Not yet. I've only started using it in a test environment while conducting code reviews. I don't know if there will be issues in the future or not, and what their nature will be: memory leaks or socket exhaustion. Or maybe there will be no problems at all. The only thing that bothers me right now is that Microsoft recommends using HttpClient differently in their documentation, and why aren't their recommendations being followed?

**Comment by franklupo** [comment]
For now there are no problems. If there are, we will change.

Best regards

**Comment by dhmhd** [comment]
Alright then. Thanks for the answers.
