### ISSUE TITLE
client.UseApiToken is Error

### ISSUE THREAD

**Issue by MickVazovsky** [Corsinvest/cv4pve-api-dotnet#4]
Corsinvest.ProxmoxVE.Api (2.4.0.0)

`client.UseApiToken("");`

Error	CS1061	'PveClient' does not contain a definition for 'UseApiToken' and no accessible extension method 'UseApiToken' accepting a first argument of type 'PveClient' could be found (are you missing a using directive or an assembly reference?)

**Comment by franklupo** [comment]
Hi,
sorry the corrent property is:
https://github.com/Corsinvest/cv4pve-api-dotnet/blob/27f37abe6a26d6070fcc16f30cd6c98a8d56bba9/src/Corsinvest.ProxmoxVE.Api/PveClientBase.cs#L83

**Comment by MickVazovsky** [comment]
var client = new PveClient("10.92.100.33");
client.ApiToken = "root@pam!qqqqqq=8a8c1cd4-d373-43f1-b366-05ce4cb8061f";
var version = client.Version.Version();
Console.WriteLine(JsonConvert.SerializeObject(version.Response.data, Formatting.Indented));


`'PveClient' does not contain a definition for 'ApiToken' and no accessible extension method 'ApiToken' accepting a first argument of type 'PveClient' could be found (are you missing a using directive or an assembly reference?)`

**Comment by franklupo** [comment]
Hi 
which version do you use?

**Comment by MickVazovsky** [comment]
Corsinvest.ProxmoxVE.Api (2.4.0.0) https://www.nuget.org/packages/Corsinvest.ProxmoxVE.Api/2.4.0

My .NetFramework 4.6.2

**Comment by franklupo** [comment]
Upgrade to last version

**Comment by MickVazovsky** [comment]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Corsinvest.ProxmoxVE.Api 2.7.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	
```

**Comment by franklupo** [comment]
The problem has been fixed in the latest version. Now it uses netStandard2.0

Best regards

**Comment by MickVazovsky** [comment]
No thanks, with the help of RestSharp did everything that was needed.
