### ISSUE TITLE
DELETE: /nodes/{node}/lxc/{vmid} returns "Unexpected content for method 'DELETE'"

### ISSUE THREAD

**Issue by AleksaDjordjic** [Corsinvest/cv4pve-api-dotnet#7]
![image](https://user-images.githubusercontent.com/33227154/144769881-6137f6f1-6e93-462c-874d-2a0603c9fddc.png)

I've tried deleting a container, with the result of `Unexpected content for method 'DELETE'` and StatusCode of NotImplemented.

.Net Version: `5.0`
cv4pve-api-dotnet Version: `7.0.1`
Proxmox Version: `7.0-13`

Steps to reproduce are quite simple:
Make a container
Try to delete it through code, with `.DestroyVm(true, true, true)`

**Comment by AleksaDjordjic** [comment]
> Hi, when execute an action the result is a task. To wait to end task use method [WaitForTaskToFinish](https://github.com/Corsinvest/cv4pve-api-dotnet/blob/master/src/Corsinvest.ProxmoxVE.Api/PveClientBase.cs#L307)
> 
> in your case
> 
> ```cs
> var task = result.Response.data;
> client.WaitForTaskToFinish(result.Response.data);
> ```

That's not what I'm aiming to do, I don't want to wait for that task to finish, instead grab its UPID and then do my own logic with it.
According to the Proxmox VE API Documentation, this should return a string object which is the UPID.

I've done a similar approach to other functions like creating backups and they work fine.

Regardless, that doesn't matter as its not the problem;
Problem is **that the task isn't even invoked/made - the request doesn't succeed, instead returns HTTP 501**

**Comment by AleksaDjordjic** [comment]
Here is the `request` object serialized:
```{
  "MethodType": 3,
  "ResponseType": 1,
  "RequestResource": "/nodes/prox1/lxc/101",
  "RequestParameters": {
    "destroy-unreferenced-disks": true,
    "force": true,
    "purge": true
  },
  "ResponseInError": false,
  "Response": {},
  "ResponseToDictionary": {},
  "StatusCode": 501,
  "ReasonPhrase": "Unexpected content for method 'DELETE'",
  "IsSuccessStatusCode": false
}```

**Comment by AleksaDjordjic** [comment]
> Hi, when execute an action the result is a task. To wait to end task use method [WaitForTaskToFinish](https://github.com/Corsinvest/cv4pve-api-dotnet/blob/master/src/Corsinvest.ProxmoxVE.Api/PveClientBase.cs#L307)
> 
> in your case
> 
> ```cs
> var task = result.Response.data;
> client.WaitForTaskToFinish(result.Response.data);
> ```

Found a potential problem with this, opened an issue about it and suggested a fix: https://github.com/Corsinvest/cv4pve-api-dotnet/issues/8

**Comment by franklupo** [comment]
Ok, found the problem. I pass the parameters as form and not in the url.
