### ISSUE TITLE
How do you use Get, Set, Create etc?

### ISSUE THREAD

**Issue by Snakzi** [Corsinvest/cv4pve-api-dotnet#9]
Hello,

thank you for this package, however I lack of understanding how it works. 
For example, I'm trying to get all users and log the response in a richTextBox:

```  
var client = new PveClient(File.ReadLines(ipList).First());
if(client.Login("root", File.ReadLines(passwordList).First()))
{
    Log("Connected to " + client.Hostname, 1);
    var users = client.Get("/access/users");
    Log(users.Response, 2);
}
```

however it does not work as supposed to. What am I doing wrong?

**Comment by franklupo** [comment]
Hi,
when call a method tre result is a class [Result](https://github.com/Corsinvest/cv4pve-api-dotnet/blob/master/src/Corsinvest.ProxmoxVE.Api/Result.cs). See result [detail](https://github.com/Corsinvest/cv4pve-api-dotnet#result).
You can also use specific methods instead of using url

```C#
   //use url
   var vm = client.get("/nodes/pve1/qemu/100");

   //use methods
    var vm = client.Nodes["pve1"].Qemu[100];
```

You are welcome

**Comment by Snakzi** [comment]
Hey,

thank you for your response. If I do this:

```
var users = client.Get("/access/users");
MessageBox.Show(users.Response);
```

I just get an error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: "The best match for the overloaded System.Windows.Forms.MessageBox.Show(string) method contains some invalid arguments."

**Comment by franklupo** [comment]
```c#
var users = client.Get("/access/users");
MessageBox.Show(users.Response.data);
```

**Comment by Snakzi** [comment]
This will also print out the same error. Do I need to somehow activate the API on the proxmox node first?
Sorry, very beginner with proxmox api here.

**Comment by franklupo** [comment]
Hi,
what version do you use dotnet?

**Comment by Snakzi** [comment]
dotnet 3.1 and framework 4.7.2

**Comment by franklupo** [comment]
Hi,

```c#
        static void Main(string[] args)
        {
            var client = new PveClient("10.92.90.101");
            if (client.Login("root", "password"))
            {
                var users = client.Access.Users.Index();
                Console.Out.WriteLine(users.Response.data);

                users = client.Get("/access/users");
                Console.Out.WriteLine(users.Response.data);
            }
        }
```
it works for me.

**Comment by Snakzi** [comment]
Hello,

that is very weird. First option does not work for me as well. Do I have to enable something on Proxmox itself first? Or choose the authentication method?

**Comment by franklupo** [comment]
The user is @pam or @pve.
The data is dynamic objec in this case a collection

**Comment by Snakzi** [comment]
Okay, thank you. How would I create a user?

**Comment by franklupo** [comment]
In result the message error?

**Comment by Snakzi** [comment]
There is no error. MessageBox is just blank

**Comment by Snakzi** [comment]
I found it now. I was just too dumb to properly read the ExpandoObject. 

However, I have a question about Permissions. If I want to assign a permission to someone, there is no parameter to choose the role I want to apply to the user.

**Comment by Snakzi** [comment]
This is solved. Thank you for your patience and help!
